### ISSUE TITLE
Not accepting user/pass

### ISSUE THREAD

**Issue by hacker213** [secureworks/squarephish#2]
not accepting the Gmail account. I have verified the username and password via GUI. I have tried on ParrotOS as well as Kali

[2023-01-04 14:51:59,327] [fail] Failed to send email: (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials e21-20020a9d0195000000b00670523bf1cfsm16936428ote.47 - gsmtp')
[2023-01-04 14:51:59,327] [fail] Failed to send QR code to victim

Settings.config
[DEFAULT]
SMTP_PORT            = 465                                                                                       # SMTP port, defaulted to 465
SMTP_SERVER          = "smtp.gmail.com"                                                              # SMTP server, defaulted to GMail
SMTP_PROTO           = "ssl"                                                                                      # SMTP protocol: {ssl, tls, None (leave empty)}
SMTP_EMAIL           = "213testemail@gmail.com"                                                  # Provide authenticating email address here
SMTP_PASSWORD        = "XXXXXXXXXXXX"                                                         # Provide authenticating password here

[EMAIL]
SQUAREPHISH_SERVER   = "192.168.1.202"                                                          # Required: Provide IP address/domain name of hosted SquarePhish server
SQUAREPHISH_PORT     = 8443                                                                     # Hosted SquarePhish server port, defaulted to 8443 (this should match the below server value)
SQUAREPHISH_ENDPOINT = "/mfa"                                                                   # Hosted SquarePhish endpoint to trigger OAuth Device Code flow, defaulted to an MFA pretext (this should match the below server value)
FROM_EMAIL           = "admin@square.phish"                                                     # Default FROM address when sending an email
SUBJECT              = "ACTION REQUIRED: Multi-Factor Authentication (MFA) Update"              # Default SUBJECT when sending an email, defauled to an MFA pretext
EMAIL_TEMPLATE       = "pretexts/mfa/qrcode_email.html"                                         # Email body template for QR code email to victim

[SERVER]
PORT                 = 8443
FROM_EMAIL           = "admin@square.phish"                                                     # Default FROM address when sending an email
SUBJECT              = "ACTION REQUIRED: Multi-Factor Authentication (MFA) Update"              # Default SUBJECT when sending an email, defauled to an MFA pretext
CLIENT_ID            = "4813382a-8fa7-425e-ab75-3b753aab3abb"                                   # Authenticating client ID, defaulted to Microsoft Authenticator App
ENDPOINT             = "/mfa"                                                                   # Hosted endpoint to trigger OAuth Device Code flow, defaulted to an MFA pretext
CERT_CRT             = ""                                                                       # Server SSL certificate .crt file
CERT_KEY             = ""                                                                       # Server SSL certificate .key file
EMAIL_TEMPLATE       = "pretexts/mfa/devicecode_email.html"                                     # Email body template for device code email to victim
PERMISSION_SCOPE     = ".default offline_access profile openid"                                 # OAuth permission scope - https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-permissions-and-consent

Thanks in advance for your time.

**Comment by nromsdahl-scwx** [comment]
I think gmail requires you to use an 'app password' instead of the actual password.  https://support.google.com/accounts/answer/185833?hl=en

**Comment by hacker213** [comment]
Thanks for the direction. Ill test today and let you know

**Comment by hacker213** [comment]
That took care of the issue. Thank you so much. I have a new error but will open a new case.
