### ISSUE TITLE
Unable to complete Authentication

### ISSUE THREAD

**Issue by hacker213** [secureworks/squarephish#3]
Thank you for the previous direction. I was able to get past the initial error, server started with no issues. When I run the workflow i am getting the following in the server log:
[2023-01-05 14:17:06,841] [info]           auth.py:56   - [213@x213x.com] Polling for user authentication...
[2023-01-05 14:17:06,842] [debug] connectionpool.py:1003 - Starting new HTTPS connection (1): login.microsoftonline.com:443
[2023-01-05 14:17:08,092] [debug] connectionpool.py:456  - https://login.microsoftonline.com:443 "POST /organizations/oauth2/v2.0/token HTTP/1.1" 400 510
[2023-01-05 14:17:08,093] [debug]           auth.py:65   - [213@x213x.com] Device code polling response:
{'error': 'authorization_pending', 'error_description': 'AADSTS70016: OAuth 2.0 device flow error. Authorization is pending. Continue polling.\r\nTrace ID: 342171d0-0d5b-42f7-8510-f64a57752400\r\nCorrelation ID: 2d132a74-e79d-43f6-a068-1f02e2c3fd19\r\nTimestamp: 2023-01-05 20:36:23Z', 'error_codes': [70016], 'timestamp': '2023-01-05 20:36:23Z', 'trace_id': '342171d0-0d5b-42f7-8510-f64a57752400', 'correlation_id': '2d132a74-e79d-43f6-a068-1f02e2c3fd19', 'error_uri': 'https://login.microsoftonline.com/error?code=70016'}

on the mobile device i am getting:

AADSTS900561: the endpoint only accepts POST requests. Received a GET request

Any direction would be great. Thank you for your time and effort into building this tool.

**Comment by nromsdahl-scwx** [comment]
The mobile device should automatically be redirected to https://login.microsoftonline.com/common/oauth2/deviceauth.  Then the target just needs to enter the device code they received in the 2nd email.  I don't know why the mobile device would be sending a post request.  When the QR code is scanned, the phones QR code reader will do a get request to the squarephish server, and then should be redirected to the above link.

Its possible, MS or something else is scanning the QR code and triggering the workflow early (I had that happen in testing).  That can be prevented by waiting a few minutes to bring up the server after sending the email.  I am not sure that is the issue though.

Hopefully that helps.

**Comment by hacker213** [comment]
It was a timing issue. Thank you again for the fast response.

Everything working, amazing tool.
